name: Weekly update
on:
  schedule:
    - cron: '0 0 * * 2' # Every Tuesday

jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm-check-updates
        run: 'npm i -g npm-check-updates'

      - name: Update all dependencies
        run: 'npm run update-all'

      - name: Create PR
        uses: peter-evans/create-pull-request@v3.10.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 'Update all dependencies'
          body: 'Update all dependencies'
          branch: 'automated/update-all-dependencies'

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
